usage:
	@echo "\tUSAGE: make sat1|sat2|ps1|ps2|ps3|ps9|ps10"

sat1:
	glpsol --math sat1.ampl

sat2:
	glpsol --math sat2.ampl

ps1:
	glpsol --math ps1.ampl

ps2:
	glpsol --math ps2.ampl

ps3:
	glpsol --math ps3.ampl

ps9:
	glpsol --math ps9.model --data ps9.data --wcpxlp ps9.lp.out

ps10:
	glpsol --math ps10.model --data ps10.data --wcpxlp ps10.lp.out
